<a href="https://colab.research.google.com/github/ParthPeswani/Breast-cancer-prediction/blob/main/breastCancer_svm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Breast Cancer Prediction svm classifier**

prediction classifier based on svm to predict cancer or not

## **importing files**

In [ ]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


## **dataset import by pandas**

dataset from uci kaggle

In [ ]:
#importing database
bc_df = pd.read_csv("/content/breastCancer.csv")

In [ ]:
# first 5 values of dataframe
bc_df.head()

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   Outcome  
0        0  
1        0  
2        0  
3        0  
4        0

In [ ]:
# shape of dataset
bc_df.shape

(569, 6)

In [ ]:
# staticsticks of data
bc_df.describe()

mean_radius  mean_texture  mean_perimeter    mean_area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean_smoothness     Outcome  
count       569.000000  569.000000  
mean          0.096360    0.627417  
std           0.014064    0.483918  
min           0.052630    0.000000  
25%           0.086370    0.000000  
50%           0.095870    1.000000  
75%           0.105300    1.000000  
max           0.163400    1.000000

In [ ]:
# our data set is supervised
# studing outcomes
bc_df['Outcome'].value_counts()

1    357
0    212
Name: Outcome, dtype: int64

In [ ]:
#we are getting '0' for non cancer and '1' for cancer

In [ ]:
bc_df.groupby('Outcome').mean()

mean_radius  mean_texture  mean_perimeter   mean_area  \
Outcome                                                          
0          17.462830     21.604906      115.365377  978.376415   
1          12.146524     17.914762       78.075406  462.790196   

         mean_smoothness  
Outcome                   
0               0.102898  
1               0.092478

----> for non cancer <-----
>outcome = 0
>area = approx 8 times perimeter
>radius is 17 or more usually

----> for cancer <-----

>outcome = 1
>area = approx 6 times perimeter
>radius is less then 12 usually



In [ ]:
# we can say cancer is more prominient in womens with radius less or equal to 12
# with approx relationship between area and perimeter our classifier will be based on these pareameters only

## **seperating outcome column**

In [ ]:
X = bc_df.drop('Outcome', axis=1)

In [ ]:
X.head()

mean_radius  mean_texture  mean_perimeter  mean_area  mean_smoothness
0        17.99         10.38          122.80     1001.0          0.11840
1        20.57         17.77          132.90     1326.0          0.08474
2        19.69         21.25          130.00     1203.0          0.10960
3        11.42         20.38           77.58      386.1          0.14250
4        20.29         14.34          135.10     1297.0          0.10030

In [ ]:
Y = bc_df['Outcome']
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Outcome, dtype: int64

# **standardizing data**

In [ ]:
scaller = StandardScaler()

In [ ]:
scaller.fit(X)

StandardScaler()

In [ ]:
standard_data = scaller.transform(X)

In [ ]:
standard_data

array([[ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633],
       [ 1.82982061, -0.35363241,  1.68595471,  1.90870825, -0.82696245],
       [ 1.57988811,  0.45618695,  1.56650313,  1.55888363,  0.94221044],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578,  0.57795264, -0.84048388],
       [ 1.83834103,  2.33645719,  1.98252415,  1.73521799,  1.52576706],
       [-1.80840125,  1.22179204, -1.81438851, -1.34778924, -3.11208479]])

In [ ]:
X = standard_data

In [ ]:
X

array([[ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633],
       [ 1.82982061, -0.35363241,  1.68595471,  1.90870825, -0.82696245],
       [ 1.57988811,  0.45618695,  1.56650313,  1.55888363,  0.94221044],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578,  0.57795264, -0.84048388],
       [ 1.83834103,  2.33645719,  1.98252415,  1.73521799,  1.52576706],
       [-1.80840125,  1.22179204, -1.81438851, -1.34778924, -3.11208479]])

In [ ]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: Outcome, Length: 569, dtype: int64

# **dividing test and training data sets**

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
X_train.shape

(455, 5)

In [ ]:
Y_train.shape

(455,)

In [ ]:
X_test.shape

(114, 5)

In [ ]:
Y_test.shape

(114,)

In [ ]:
Y_train # we have used stratify means outcome is randomly divided

23     0
316    1
251    1
391    1
444    0
      ..
71     1
233    0
346    1
17     0
75     0
Name: Outcome, Length: 455, dtype: int64

In [ ]:
Y_test

223    0
418    1
246    1
387    1
407    1
      ..
467    1
108    0
430    0
129    0
188    1
Name: Outcome, Length: 114, dtype: int64

## **building svm classifier (Training)**

In [ ]:
classifier = svm.SVC(kernel='linear')

In [ ]:
#training svm

In [ ]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

## **checking underfit**

In [ ]:
X_train_predictions = classifier.predict(X_train)

In [ ]:
X_train_predictions

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,

In [ ]:
training_data_accuracy = accuracy_score(X_train_predictions,Y_train)

In [ ]:
training_data_accuracy

0.9296703296703297

In [ ]:
# means data classifier is 92% accurate with training data means not underfit

## **Testing data analysis (overfit check)**

In [ ]:
Y_testing_predictions = classifier.predict(X_test)

In [ ]:
Y_testing_predictions

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1])

In [ ]:
testing_data_accuracy = accuracy_score(Y_testing_predictions,Y_test)

In [ ]:
testing_data_accuracy

0.9298245614035088

In [ ]:
# 93% accurate with testing data means not overfit

# Taking randomn input from data set

In [ ]:
input = (20.57,17.77,132.9,1326,0.08474) #0
#input = (13.54,14.36,87.46,566.3,0.09779) #1

In [ ]:
# converting to numpy array
input_arr = np.asarray(input)

In [ ]:
input_arr

array([2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02])

In [ ]:
reshaped_arr = input_arr.reshape(1,-1)

In [ ]:
reshaped_arr.shape

(1, 5)

In [ ]:
reshaped_arr

array([[2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02]])

In [ ]:
#standardizing data
std_data = scaller.transform(reshaped_arr)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
std_data

array([[ 1.82982061, -0.35363241,  1.68595471,  1.90870825, -0.82696245]])

In [ ]:
prediction = classifier.predict(std_data)

In [ ]:
print(prediction)
if(prediction[0]==0):
  print("person is predicted to not having breast cancer")
else:
  print("person is predicted to having breast cancer")

[0]
person is predicted to not having breast cancer
